version: '3.7'
services:
  web:
    build: ./django_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_site/:/Documents/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine

    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev



    
