# Generated by Django 3.2.7 on 2021-12-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account_comment_tag'),
        ('blog', '0002_auto_20211218_2149'),
    ]

    operations = [
    ]
